---
    - name: Multi user creation
      hosts: localhost
      connection: local
      tasks:
              - name: Creating user
                user:
                    name: "{{item}}"
                    state: present
                loop:
                          - abida
                          - Sabia
                          - Rahman
              - name: run cat /etc/passwd
                command: cat /etc/passwd
                register: usrdetails
                notify:
                        -  showpwd
      handlers:
              - name: showpwd
                debug:
                       var:
                               usrdetails
